import './styles.css';
import { DayWeather, PackingItem, TripInput, dayCount, generatePackingList } from './rules';
import { demoWeatherFor } from './weather';

const storageKey = 'packcast-trip-v1';
const app = document.querySelector<HTMLDivElement>('#app')!;
const activities = ['Sightseeing', 'Business', 'Formal event', 'Hiking', 'Beach / pool', 'Gym / running', 'Dinner out', 'Snow activities'];
const categories = ['Clothing', 'Footwear', 'Weather Gear', 'Activity Gear', 'Toiletries', 'Electronics', 'Documents', 'Misc'];

interface SavedTrip { input: TripInput; weather: DayWeather[]; items: PackingItem[]; }
let saved: SavedTrip | null = JSON.parse(localStorage.getItem(storageKey) ?? 'null');

const formatDate = (date: string) => new Intl.DateTimeFormat('en', { weekday: 'short', month: 'short', day: 'numeric' }).format(new Date(`${date}T12:00:00`));
const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character] ?? character));

function renderSetup(message = '') {
  const savedInput = saved?.input;
  app.innerHTML = `<main class="shell setup-shell"><header class="topbar"><div class="brand"><span class="brand-mark">P</span><span>PackCast</span></div><span class="eyebrow">TRIP PLANNER</span></header><section class="intro"><p class="kicker">PACK WITH CONFIDENCE</p><h1>Bring what the<br><em>weather</em> calls for.</h1><p class="lede">A thoughtful packing list for the trip you are actually taking.</p></section><form id="trip-form" class="trip-form"><label>Destination<input name="destination" placeholder="e.g. Lisbon, Portugal" value="${escapeHtml(savedInput?.destination ?? '')}" required /></label><div class="field-row"><label>Start date<input type="date" name="startDate" value="${savedInput?.startDate ?? ''}" required /></label><label>End date<input type="date" name="endDate" value="${savedInput?.endDate ?? ''}" required /></label></div><fieldset><legend>What are you doing?</legend><div class="chips">${activities.map((activity) => `<label class="chip"><input type="checkbox" name="activity" value="${activity}" ${savedInput?.activities.includes(activity) ? 'checked' : ''} /><span>${activity}</span></label>`).join('')}</div></fieldset><div class="field-row option-row"><label>Temperature<select name="units"><option value="F" ${savedInput?.units !== 'C' ? 'selected' : ''}>Fahrenheit</option><option value="C" ${savedInput?.units === 'C' ? 'selected' : ''}>Celsius</option></select></label><label>Laundry<select name="laundry"><option value="no" ${!savedInput?.laundry ? 'selected' : ''}>No laundry</option><option value="yes" ${savedInput?.laundry ? 'selected' : ''}>Laundry available</option></select></label></div><label class="toggle-line"><input type="checkbox" name="carryOn" ${savedInput?.luggage === 'carry-on' ? 'checked' : ''} /><span>I'm packing carry-on only</span></label>${message ? `<p class="form-error">${message}</p>` : ''}<button class="primary-button" type="submit">Build my packing list <span>→</span></button></form></main>`;
  document.querySelector<HTMLFormElement>('#trip-form')!.addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const selected = form.getAll('activity').map(String); const startDate = String(form.get('startDate')); const endDate = String(form.get('endDate')); if (!selected.length) return renderSetup('Choose at least one activity to shape your list.'); if (dayCount(startDate, endDate) < 1) return renderSetup('End date must be on or after the start date.'); const input: TripInput = { destination: String(form.get('destination')).trim(), startDate, endDate, activities: selected, laundry: form.get('laundry') === 'yes', luggage: form.get('carryOn') ? 'carry-on' : 'checked', units: form.get('units') as 'F' | 'C' }; save({ input, weather: demoWeatherFor(input), items: [] }, true); });
}

function save(value: SavedTrip, generate = false) { if (generate) value.items = generatePackingList(value.input, value.weather); saved = value; localStorage.setItem(storageKey, JSON.stringify(value)); renderList(); }
function renderList(changeNote = '') {
  if (!saved) return renderSetup();
  const { input, weather, items } = saved; const checked = items.filter((item) => item.checked).length; const climate = weather.some((day) => day.source === 'climate');
  app.innerHTML = `<main class="shell list-shell"><header class="topbar"><button class="text-button" id="edit-trip">← Edit trip</button><div class="brand"><span class="brand-mark">P</span><span>PackCast</span></div><button class="icon-button" id="refresh" title="Refresh weather">↻</button></header><section class="list-heading"><p class="kicker">YOUR PACKING LIST</p><h1>${escapeHtml(input.destination)}</h1><p class="trip-meta">${formatDate(input.startDate)} – ${formatDate(input.endDate)} <span>·</span> ${input.activities.map(escapeHtml).join(' · ')}</p><div class="weather-label"><span class="status-dot"></span>${climate ? 'Based on typical weather' : 'Forecast outlook'} <span class="muted">· Updated just now</span></div></section><section class="weather-strip">${weather.map((day) => `<div class="weather-day"><span>${formatDate(day.date).split(',')[0]}</span><strong>${day.icon === 'RAIN' ? '☂' : '☀'}</strong><b>${Math.round(day.high)}°</b><small>${Math.round(day.low)}°</small></div>`).join('')}</section><section class="progress-block"><div><span>PACKING PROGRESS</span><strong>${checked} / ${items.length} items</strong></div><div class="progress"><i style="width:${items.length ? checked / items.length * 100 : 0}%"></i></div></section>${changeNote ? `<div class="change-note">${escapeHtml(changeNote)}</div>` : ''}<section class="items">${categories.map((category) => { const categoryItems = items.filter((item) => item.category === category); if (!categoryItems.length) return ''; return `<div class="category"><div class="category-title"><h2>${category}</h2><span>${categoryItems.filter((item) => item.checked).length}/${categoryItems.length}</span></div>${categoryItems.map(itemTemplate).join('')}</div>`; }).join('')}</section><form id="add-form" class="add-form"><input name="name" placeholder="Add an item" aria-label="Add an item" required /><button title="Add item">+</button></form></main>`;
  document.querySelector('#edit-trip')!.addEventListener('click', () => renderSetup()); document.querySelector('#refresh')!.addEventListener('click', () => { const previousItems = saved!.items; saved!.weather = demoWeatherFor(input); const nextItems = generatePackingList(input, saved!.weather).map((item) => ({ ...item, checked: Boolean(previousItems.find((old) => old.id === item.id)?.checked) })); const changed = nextItems.length !== previousItems.length || nextItems.some((item) => !previousItems.some((old) => old.id === item.id)); saved!.items = nextItems; localStorage.setItem(storageKey, JSON.stringify(saved)); renderList(changed ? 'Weather refreshed. Your recommendations changed.' : 'Weather refreshed. Your recommendations are unchanged.'); });
  document.querySelectorAll<HTMLInputElement>('[data-item-check]').forEach((box) => box.addEventListener('change', () => { const item = saved!.items.find((entry) => entry.id === box.dataset.itemCheck); if (item) item.checked = box.checked; localStorage.setItem(storageKey, JSON.stringify(saved)); renderList(); }));
  document.querySelectorAll<HTMLButtonElement>('[data-delete]').forEach((button) => button.addEventListener('click', () => { saved!.items = saved!.items.filter((item) => item.id !== button.dataset.delete); save(saved!); }));
  document.querySelectorAll<HTMLInputElement>('[data-quantity]').forEach((input) => input.addEventListener('change', () => { const item = saved!.items.find((entry) => entry.id === input.dataset.quantity); if (item) item.quantity = Math.max(1, Number(input.value) || 1); save(saved!); }));
  document.querySelector<HTMLFormElement>('#add-form')!.addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const name = String(form.get('name')).trim(); if (name) saved!.items.push({ id: `user-${Date.now()}`, name, category: 'Misc', quantity: 1, reasons: ['Added by you'], sources: ['user'], checked: false }); save(saved!); });
}
function itemTemplate(item: PackingItem) { return `<div class="item-row ${item.checked ? 'is-checked' : ''}"><label><input type="checkbox" data-item-check="${item.id}" ${item.checked ? 'checked' : ''} /><span class="checkmark"></span><span class="item-copy"><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.reasons[0] ?? '')}</small></span></label><input class="quantity" type="number" min="1" value="${item.quantity}" data-quantity="${item.id}" aria-label="Quantity for ${escapeHtml(item.name)}" /><button class="delete-button" data-delete="${item.id}" title="Remove item">×</button></div>`; }

saved ? renderList() : renderSetup();